# Generated by Django 5.0.6 on 2024-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeds",
            name="activity_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feeds",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="feeds",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_in_feeds", to="project_app.member"
            ),
        ),
        migrations.DeleteModel(
            name="feeds_posts",
        ),
    ]
