# Generated by Django 5.0.1 on 2024-07-21 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp_bosun", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeds",
            name="pages",
            field=models.ManyToManyField(
                blank=True, related_name="feeds_pages", to="myapp_bosun.pages"
            ),
        ),
        migrations.AddField(
            model_name="feeds",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="feeds_posts", to="myapp_bosun.posts"
            ),
        ),
        migrations.AddField(
            model_name="feeds",
            name="threads",
            field=models.ManyToManyField(
                blank=True, related_name="feeds_threads", to="myapp_bosun.threads"
            ),
        ),
        migrations.AddField(
            model_name="pagescomments",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages_comments",
                to="myapp_bosun.feeds",
            ),
        ),
        migrations.AddField(
            model_name="postcomments",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_comments",
                to="myapp_bosun.feeds",
            ),
        ),
        migrations.AddField(
            model_name="threadcomments",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads_comments",
                to="myapp_bosun.feeds",
            ),
        ),
        migrations.AlterField(
            model_name="pages",
            name="feed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages_related",
                to="myapp_bosun.feeds",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="feed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_related",
                to="myapp_bosun.feeds",
            ),
        ),
        migrations.AlterField(
            model_name="threads",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads_related",
                to="myapp_bosun.feeds",
            ),
        ),
    ]
