# Generated by Django 5.0.1 on 2024-07-21 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp_bosun", "0002_feeds_pages_feeds_posts_feeds_threads_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="email_id",
        ),
    ]
