# Generated by Django 5.0.6 on 2024-07-13 20:38

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
                ('cover_picture', models.ImageField(upload_to='cover_pictures')),
                ('interests', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('followee_id', models.ManyToManyField(related_name='following', to='myapp.member')),
                ('follower_id', models.ManyToManyField(related_name='followers', to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='feeds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Pages_comments',
            fields=[
                ('pages_comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('upvote', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0)),
                ('downvote', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Pages_followers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('follower_id', models.ManyToManyField(related_name='followers_pages', to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadComments',
            fields=[
                ('thread_comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('upvote', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0)),
                ('downvote', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('thread_id', models.IntegerField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='feeds_posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.feeds')),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.threads')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.threads')),
            ],
        ),
    ]
