# Generated by Django 5.0.6 on 2024-07-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='request_id',
            field=models.ManyToManyField(related_name='requests', to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='followee_id',
            field=models.ManyToManyField(choices=[(1, 'Request'), (2, 'Following')], related_name='following', to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower_id',
            field=models.ManyToManyField(choices=[(1, 'Request'), (2, 'Following')], related_name='followers', to='myapp.member'),
        ),
    ]
