# Generated by Django 5.0.7 on 2024-07-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='feeds_posts',
            name='feed_id',
        ),
        migrations.RemoveField(
            model_name='feeds_posts',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='followee_id',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='feeds',
        ),
        migrations.DeleteModel(
            name='feeds_posts',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
