# Generated by Django 5.0.7 on 2024-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followee_id',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower_id',
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
