# Generated by Django 5.0.6 on 2024-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_followers_request_id_alter_followers_followee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('caption', models.CharField(max_length=255)),
                ('video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
            ],
        ),
    ]
