# Generated by Django 5.0.7 on 2024-07-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sitevisit_followers_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
