# Generated by Django 5.0.6 on 2024-07-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pages_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_comments',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
    ]
