# Generated by Django 5.0.6 on 2024-07-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pages_comments_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_comments',
            name='pages_comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
