# Generated by Django 5.0.7 on 2024-07-12 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_member_email_id_remove_member_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='user_id',
        ),
    ]
