# Generated by Django 5.0.6 on 2024-07-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pages_comments_pages_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_followers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
