# Generated by Django 5.0.6 on 2024-07-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pages_followers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages_comments',
            name='downvote',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='pages_comments',
            name='upvote',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1),
        ),
    ]
