# Generated by Django 5.0.6 on 2024-07-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_pages_comments_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages_followers',
            name='page_id',
            field=models.ForeignKey(default=202407171858142, on_delete=django.db.models.deletion.CASCADE, to='myapp.pages'),
        ),
    ]
