# Generated by Django 5.0.6 on 2024-07-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sessioncount_sitevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages_followers',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='pages_followers',
            name='follower_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
    ]
