# Generated by Django 5.0.6 on 2024-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_pages_followers_follower_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('Title', models.CharField(max_length=255)),
                ('video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d')),
            ],
        ),
    ]
