# Generated by Django 5.0.6 on 2024-07-21 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
        migrations.CreateModel(
            name='Video_comments',
            fields=[
                ('video_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('upvote', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('downvote', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.video')),
            ],
        ),
    ]
