# Generated by Django 5.0.6 on 2024-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_video_uploaded_by_video_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='followee',
            new_name='followee_id',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='follower_id',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='status',
        ),
        migrations.AddField(
            model_name='followers',
            name='request_id',
            field=models.ManyToManyField(related_name='requests', to='myapp.member'),
        ),
    ]
