# Generated by Django 5.0.6 on 2024-07-22 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_followee_followers_followee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favourites'},
        ),
        migrations.AlterModelOptions(
            name='feeds',
            options={'verbose_name_plural': 'Feeds'},
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='feeds',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='post',
        ),
        migrations.AddField(
            model_name='feeds',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='feeds_pages', to='myapp.pages'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='feeds_posts', to='myapp.posts'),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1)),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_related', to='myapp.feeds')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'verbose_name_plural': 'Threads',
            },
        ),
        migrations.CreateModel(
            name='ThreadComments',
            fields=[
                ('thread_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads_comments', to='myapp.feeds')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
                ('thread_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.threads')),
            ],
            options={
                'verbose_name_plural': 'ThreadComments',
            },
        ),
        migrations.AddField(
            model_name='favorites',
            name='thread_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.threads'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='feeds_threads', to='myapp.threads'),
        ),
    ]
