# Generated by Django 5.0.6 on 2024-07-23 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('follow', 'Follow Notification'), ('post', 'post Notification'), ('video_like', 'Video Like Notification'), ('post_like', 'Post Like Notification'), ('video_comment', 'Video Comment Notification'), ('post_comment', 'Post Comment Notification'), ('page_comment', 'Page Comment Notification'), ('event', 'Event Notification'), ('page_like', 'Page like Notification'), ('page_dislike', 'Page dislike Notification'), ('video_comment', 'Video Comment Notification'), ('video_dislike', 'Video disLike Notification')], max_length=15)),
                ('message', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='myapp.member')),
            ],
        ),
    ]
