# Generated by Django 5.0.6 on 2024-07-26 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media_related', to='myapp.feeds'),
        ),
        migrations.AddField(
            model_name='posts',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts_related', to='myapp.feeds'),
        ),
    ]
