# Generated by Django 5.0.6 on 2024-07-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_mediacontent_created_at_mediacontent_feed_posts_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='feeds_media', to='myapp.mediacontent'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='feeds_videos', to='myapp.video'),
        ),
    ]
