# Generated by Django 5.0.6 on 2024-07-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_feeds_media_feeds_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos_related', to='myapp.feeds'),
        ),
    ]
