# Generated by Django 5.0.7 on 2024-07-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%y'),
        ),
    ]
